Destination details
techeduk8r/who-travels pull request #11
Opened 2021-12-05 22:34 UTC by techeduk8r

Detail destination pages created (2 examples). Still need button styling, but otherwise, pages are complete.

2021-12-06 05:01 UTC, loganmorganml1 requested changes
More of a question than request, see comment attached.

2021-12-06 05:01 UTC, loganmorganml1 commented on .gitignore
> +dest-details.css
I see you've added the css for this in the main styles file, but this is linked to the seperate css file you've created. Do you want to link to the `style.css` before merging?

2021-12-06 15:14 UTC, techeduk8r commented on .gitignore
> +dest-details.css
Thanks for catching that! This file was after I lost all of the destination code and I forgot that small but important piece. It's all updated.

2021-12-07 04:31 UTC, loganmorganml1 approved these changes
Looks good, approved!

2021-12-07 04:31 UTC, merged