Insta edits
techeduk8r/who-travels pull request #35
Opened 2021-12-11 21:16 UTC by lala-laura

Instagram section pull request

2021-12-11 21:19 UTC, lala-laura commented
Hold on, there's something I need to fix

2021-12-12 00:01 UTC, loganmorganml1 requested changes
One edit, but looking good!

2021-12-12 00:01 UTC, loganmorganml1 commented on assets/css/style.css
> +  font-size: 45px;
I would keep this the same as the other h3 stylings, which would be 35px for mobile and tablet, and 55px for desktop. The desktop size looks fine but the size for other screen sizes need to go down (they are currently at 42px)

2021-12-12 17:03 UTC, loganmorganml1 approved these changes
Nothing to show, looks like it was merged cleanly!

2021-12-12 17:03 UTC, merged